# LCNN configuration
# For SigmoidLoss with binary classification (1 output)

model:
  _target_: src.model.model.LCNN
  in_channels: 1
  num_classes: 1  # One output for binary classification
  dropout_rate: 0.5 