defaults:
  - _self_
  - model: lcnn
  - optimizer: adam
  - lr_scheduler: step
  - loss_function: crossentropy
  - metrics: default
  - datasets: asvspoof2019
  - dataloader: default
  - transforms: default
  - writer: cometml  # Re-enabled CometML
  - trainer: default

data_path: ${oc.env:DATA_PATH,data}
project_name: anti-spoofing
run_name: baseline-experiment

# Settings according to the paper
trainer:
  n_epochs: 200
  log_step: 50
  monitor: min dev_eer
  early_stop: 20

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  weight_decay: 0.0001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 20
  gamma: 0.1

