# Mel-spectrogram + LCNN configuration
# Based on ASVspoof2019 paper architecture

defaults:
  - model: lcnn_lstm
  - transforms: lfcc
  - loss_function: msep2sgrad
  - optimizer: adam
  - lr_scheduler: step
  - trainer: default
  - metrics: default
  - writer: cometml
  - datasets: asvspoof2019
  - _self_

# Training configuration
trainer:
  epochs: 100  # Increased number of epochs
  eval_period: 2
  save_period: 5  # Save model every 5 epochs
  log_step: 100
  monitor: min eval_eer
  early_stop: 20  # Increased early stopping
  seed: 42

# Data configuration
dataloader:
  batch_size: 8
  num_workers: 2
  pin_memory: True
  drop_last: True

# Model configuration
model:
  dropout_rate: 0.5  # Reduced for stability

# Optimizer configuration
optimizer:
  lr: 1e-4  # Reduced learning rate
  weight_decay: 1e-4

# Learning rate scheduler
lr_scheduler:
  step_size: 10
  gamma: 0.5

# Data path configuration
data_path: ${oc.env:DATA_PATH,data}

# Transforms configuration (LFCC - best performing front-end according to paper)
transforms:
  instance_transforms:
    data_object:
      _target_: src.transforms.stft.LFCC
      fl: 320
      fs: 160
      fn: 512
      sr: 16000
      filter_num: 20
      with_energy: True
      with_emphasis: True
      with_delta: True
      flag_for_LFB: False
      num_coef: 20
      min_freq: 0
      max_freq: 1 