# Mel-spectrogram + LCNN configuration
# Based on ASVspoof2019 paper architecture

defaults:
  - model: lcnn_lstm
  - transforms: melspec
  - loss_function: bce
  - optimizer: adam
  - lr_scheduler: step
  - trainer: default
  - metrics: default
  - writer: cometml
  - datasets: asvspoof2019
  - _self_

# Training configuration
trainer:
  epochs: 30
  eval_period: 2
  save_period: 10
  log_step: 100
  monitor: min eval_eer
  early_stop: 10
  seed: 42

# Data configuration
dataloader:
  batch_size: 8
  num_workers: 2
  pin_memory: True
  drop_last: True

# Model configuration
model:
  dropout_rate: 0.5  # Reduced for stability

# Optimizer configuration
optimizer:
  lr: 1e-3
  weight_decay: 1e-4

# Learning rate scheduler
lr_scheduler:
  step_size: 10
  gamma: 0.5

# Data path configuration
data_path: ${oc.env:DATA_PATH,data}

# Transforms configuration (mel-spectrogram)
transforms:
  instance_transforms:
    data_object:
      _target_: src.transforms.stft.MelSpectrogram
      sample_rate: 16000
      n_fft: 512
      hop_length: 160
      win_length: 320
      n_mels: 80
      f_min: 0.0
      f_max: 8000.0
      power: 2.0
      with_emphasis: True
      with_delta: False
      in_db: True 