defaults:
  - _self_
  - model: lcnn_lstm_sum  # Best model from paper
  - optimizer: adam
  - lr_scheduler: step
  - loss_function: asoftmax  # Best loss function
  - metrics: default
  - datasets: asvspoof2019
  - dataloader: default
  - transforms: default
  - writer: cometml
  - trainer: default

data_path: ${oc.env:DATA_PATH,data}
project_name: anti-spoofing
run_name: baseline-optimized-experiment 