defaults:
  - _self_
  - model/lcnn
  - metrics: default
  - datasets: asvspoof2019
  - dataloader: default
  - transforms: melspec
  - writer: cometml




inferencer:
  seed: 42
  device: "auto"
  from_pretrained: "bestmodel/checkpoint-epoch6.pth" 
  save_path: "inference_results"
  log_metrics: true
  save_predictions: true
  device_tensors: ["data_object", "labels"]


data_path: ${oc.env:DATA_PATH,data}

# Transforms configuration (Mel-spectrogram)
transforms:
  instance_transforms:
    data_object:
      _target_: src.transforms.stft.MelSpectrogram
      sample_rate: 16000
      n_fft: 512
      hop_length: 160
      win_length: 320
      n_mels: 80
      f_min: 0.0
      f_max: 8000.0
      power: 2.0
      with_emphasis: True
      with_delta: False
      in_db: True

project_name: anti-spoofing-inference
run_name: inference-test

dataloader:
  eval:
    _target_: torch.utils.data.DataLoader
    batch_size: 32
    num_workers: 4
    pin_memory: true
    shuffle: false 