defaults:
  - _self_
  - model/lcnn_lstm
  - metrics: default
  - datasets: asvspoof2019
  - dataloader: default
  - transforms: lfcc
  - writer: cometml




inferencer:
  seed: 42
  device: "auto"
  from_pretrained: "bestmodel/checkpoint-epoch6.pth" 
  save_path: "inference_results"
  log_metrics: true
  save_predictions: true
  device_tensors: ["data_object", "labels"]


data_path: ${oc.env:DATA_PATH,data}

# Transforms configuration
transforms:
  instance_transforms:
    data_object:
      _target_: src.transforms.stft.LFCC
      fl: 320
      fs: 160
      fn: 512
      sr: 16000
      filter_num: 20
      with_energy: True
      with_emphasis: True
      with_delta: True
      flag_for_LFB: False
      num_coef: 20
      min_freq: 0
      max_freq: 1

project_name: anti-spoofing-inference
run_name: inference-test

dataloader:
  eval:
    _target_: torch.utils.data.DataLoader
    batch_size: 32
    num_workers: 4
    pin_memory: true
    shuffle: false 