# LFCC + LCNN-LSTM + BCE configuration
# Simplified architecture for binary classification with sigmoid

defaults:
  - model: lcnn
  - transforms: lfcc
  - loss_function: bce
  - optimizer: adam
  - lr_scheduler: step
  - trainer: default
  - metrics: default
  - writer: cometml
  - datasets: asvspoof2019
  - _self_

# Training configuration
trainer:
  epochs: 50
  eval_period: 2
  save_period: 10
  log_step: 100
  monitor: min eer
  early_stop: 10

# Data configuration
dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: True
  drop_last: True

# Model configuration
model:
  dropout_rate: 0.5

# Optimizer configuration
optimizer:
  lr: 1e-3
  weight_decay: 1e-4

# Learning rate scheduler
lr_scheduler:
  step_size: 10
  gamma: 0.5

# Data path configuration
data_path: ${oc.env:DATA_PATH,data}

# Transforms configuration
transforms:
  instance_transforms:
    data_object:
      _target_: src.transforms.stft.LFCC
      fl: 320
      fs: 160
      fn: 512
      sr: 16000
      filter_num: 20
      with_energy: True
      with_emphasis: True
      with_delta: True
      flag_for_LFB: False
      num_coef: 20
      min_freq: 0
      max_freq: 1 