# 2 основные аугментации для anti-spoofing

# Основная комбинация аугментаций
anti_spoofing:
  _target_: src.transforms.augmentations.get_anti_spoofing_augmentations
  p: 0.2

# Индивидуальные аугментации
add_noise:
  _target_: src.transforms.augmentations.AddNoise
  noise_level_range: [0.001, 0.01]
  p: 0.2

time_masking:
  _target_: src.transforms.augmentations.TimeMasking
  mask_ratio_range: [0.1, 0.3]
  p: 0.2 