instance_transforms:
  data_object: ${transforms.stft}
  # Augmentations are applied only to train data
  augmentation: ${transforms.augmentations.anti_spoofing}

# Augmentation configurations
augmentations:
  anti_spoofing:
    _target_: src.transforms.augmentations.get_anti_spoofing_augmentations
    p: 0.2

# STFT according to the paper (FFT in the paper)
stft:
  _target_: src.transforms.stft.STFTTransform
  sample_rate: 16000
  n_fft: 512
  hop_length: 160  # 10ms at 16kHz
win_length: 320  # 20ms at 16kHz

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]