instance_transforms:
  data_object: ${transforms.stft}
  # Аугментации применяются только к train данным
  augmentation: ${transforms.augmentations.anti_spoofing}

# Конфигурации аугментаций
augmentations:
  anti_spoofing:
    _target_: src.transforms.augmentations.get_anti_spoofing_augmentations
    p: 0.2

# STFT согласно статье (FFT в статье)
stft:
  _target_: src.transforms.stft.STFTTransform
  sample_rate: 16000
  n_fft: 512
  hop_length: 160  # 10ms при 16kHz
  win_length: 320  # 20ms при 16kHz

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]