# Default transforms configuration
# Simplified for LFCC only

transforms:
  # LFCC frontend configuration
  lfcc:
    frame_length: 320  # 20ms at 16kHz
    frame_shift: 160   # 10ms at 16kHz
    n_fft: 512
    sample_rate: 16000
    filter_num: 20
    with_energy: True
    with_emphasis: True
    with_delta: True
    num_coef: 20

  # Instance transforms configuration
  instance_transforms:
    data_object:
      _target_: src.transforms.stft.LFCC
      fl: 320
      fs: 160
      fn: 512
      sr: 16000
      filter_num: 20
      with_energy: True
      with_emphasis: True
      with_delta: True
      flag_for_LFB: False
      num_coef: 20
      min_freq: 0
      max_freq: 1

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]