instance_transforms:
  data_object: ${transforms.stft}

stft:
  _target_: src.transforms.stft.STFTTransform
  n_fft: 1724  # Для получения 863 freq bins (1724//2 + 1 = 863)
  hop_length: 256  # Для лучшего временного разрешения
  win_length: 1724

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]