instance_transforms:
  data_object: ${transforms.lfcc}

lfcc:
  _target_: src.transforms.lfcc.LFCCTransform
  sample_rate: 16000
  n_fft: 512
  hop_length: 160
  win_length: 320
  n_filter: 20
  n_lfcc: 20
  use_deltas: true

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]