instance_transforms:
  data_object: ${transforms.stft}

stft:
  _target_: src.transforms.stft.STFTTransform
  n_fft: 1724  # Для получения 863 freq bins (1724//2 + 1 = 863)
  hop_length: 256  # Для лучшего временного разрешения
  win_length: 1724

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        # Логарифмирование спектрограммы - критически важно для аудио
        - _target_: src.transforms.stft.LogTransform
          eps: 1e-6
        # Нормализация логарифмированных значений
        - _target_: src.transforms.normalize.Normalize
          mean: [-4.0]  # Подходящее для log-спектрограмм  
          std: [4.0]    # Подходящее стандартное отклонение
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        # Те же трансформации для inference
        - _target_: src.transforms.stft.LogTransform
          eps: 1e-6
        - _target_: src.transforms.normalize.Normalize
          mean: [-4.0]
          std: [4.0]