instance_transforms:
  data_object: ${transforms.stft}

stft:
  _target_: src.transforms.stft.STFTTransform
  n_fft: 1024
  hop_length: 512
  win_length: 1024

batch_transforms: null  # Убрали нормализацию для отладки