# LFCC frontend configuration
# Simplified version without augmentations

transforms:
  lfcc:
    _target_: src.transforms.stft.LFCC
    fl: 320
    fs: 160
    fn: 512
    sr: 16000
    filter_num: 20
    with_energy: True
    with_emphasis: True
    with_delta: True
    flag_for_LFB: False
    num_coef: 20
    min_freq: 0
    max_freq: 1

  instance_transforms:
    data_object:
      _target_: src.transforms.stft.LFCC
      fl: 320
      fs: 160
      fn: 512
      sr: 16000
      filter_num: 20
      with_energy: True
      with_emphasis: True
      with_delta: True
      flag_for_LFB: False
      num_coef: 20
      min_freq: 0
      max_freq: 1

batch_transforms:
  _target_: src.datasets.collate.CollateFn 