transforms:
  melspec:
    sample_rate: 16000
    n_fft: 512
    hop_length: 160
    win_length: 320
    n_mels: 80
    f_min: 0.0
    f_max: 8000.0
    power: 2.0
    with_emphasis: True
    with_delta: False
    in_db: True

  instance_transforms:
    data_object:
      _target_: src.transforms.stft.MelSpectrogram
      sample_rate: 16000
      n_fft: 512
      hop_length: 160
      win_length: 320
      n_mels: 80
      f_min: 0.0
      f_max: 8000.0
      power: 2.0
      with_emphasis: True
      with_delta: False
      in_db: True

batch_transforms:
  train:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]
  inference:
    data_object:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: src.transforms.normalize.Normalize
          mean: [0.0]
          std: [1.0]