seed: 42
device: auto
n_epochs: 200  # Increased for better convergence
save_period: 5
val_period: 1
skip_oom: true
max_grad_norm: 0.5
log_step: 50
save_dir: checkpoints
device_tensors:
  - data_object
  - labels
monitor: min dev_eer  # Changed from val_eer to dev_eer
early_stop: 20 
override: True