seed: 42
device: auto
n_epochs: 200  # Increased for better convergence
save_period: 5  # Save model every 5 epochs
eval_period: 2  # Changed: eval evaluation every 2 epochs from the beginning
skip_oom: true
max_grad_norm: 0.5
log_step: 50
save_dir: models
device_tensors:
  - data_object
  - labels
monitor: min train_eer  # Monitor train EER which is available every epoch
early_stop: 20 
override: True