seed: 42
device: auto
n_epochs: 200  # Increased for better convergence
save_period: 7
val_period: 10  # Changed: dev evaluation every 10 epochs (first 10 epochs without eval)
eval_period: 10  # Changed: eval evaluation every 10 epochs (first 10 epochs without eval)
skip_oom: true
max_grad_norm: 0.5
log_step: 50
save_dir: models
device_tensors:
  - data_object
  - labels
monitor: min dev_eer  # Changed from val_eer to dev_eer
early_stop: 20 
override: True