seed: 42
device: auto
n_epochs: 200  # Increased for better convergence
save_period: 7
val_period: 2  # Changed: dev evaluation every 2 epochs
eval_period: 3  # Added: eval evaluation every 3 epochs
skip_oom: true
max_grad_norm: 0.5
log_step: 50
save_dir: models
device_tensors:
  - data_object
  - labels
monitor: min dev_eer  # Changed from val_eer to dev_eer
early_stop: 20 
override: True