_target_: src.logger.cometml.CometMLWriter
project_name: "anti-spoofing"
workspace: null
run_id: null
run_name: "training-experiment"
mode: "online"
loss_names: ["loss"]
log_checkpoints: False
id_length: 8
api_key: ${oc.env:COMET_API_KEY}